// docs/src/components/FullViewerDemo.tsx
import React from "react";
import styles from "./FullViewerDemo.module.css";

interface Props {
  height?: string;
}

export default function FullViewerDemo({ height = "600px" }: Props) {
  return (
    <div className={styles.fullViewerDemo}>
      <iframe
        src="/megane/app/"
        title="megane molecular viewer"
        style={{ height }}
        frameBorder={0}
        allow="fullscreen"
        loading="lazy"
      />
    </div>
  );
}

// docs/.vitepress/components/FullViewerDemo.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    height?: string;
  }>(),
  {
    height: "600px",
  }
);
</script>

<template>
  <div class="full-viewer-demo">
    <iframe
      src="/megane/app/"
      :style="{ height }"
      frameborder="0"
      allow="fullscreen"
      loading="lazy"
    />
  </div>
</template>

<style scoped>
.full-viewer-demo {
  margin: 16px 0;
  border-radius: 12px;
  overflow: hidden;
  border: 1px solid var(--vp-c-divider);
}

.full-viewer-demo iframe {
  width: 100%;
  display: block;
  background: #fff;
}
</style>
