// docs/src/components/NotebookRenderer.tsx
import React, { useState, useEffect } from "react";

interface Props {
  src: string;
}

export default function NotebookRenderer({ src }: Props) {
  const [html, setHtml] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(src)
      .then((r) => r.text())
      .then((text) => {
        setHtml(text);
        setLoading(false);
      });
  }, [src]);

  if (loading) {
    return (
      <div style={{ padding: "2rem", textAlign: "center", color: "var(--ifm-color-emphasis-600)" }}>
        Loading notebook...
      </div>
    );
  }

  return (
    <div
      className="nb-container"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

// docs/.vitepress/components/NotebookRenderer.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

const props = defineProps<{ src: string }>();

const html = ref("");
const loading = ref(true);

onMounted(async () => {
  const res = await fetch(props.src);
  html.value = await res.text();
  loading.value = false;
});
</script>

<template>
  <div v-if="loading" class="nb-loading">Loading notebook...</div>
  <div v-else class="nb-container" v-html="html" />
</template>

<style scoped>
.nb-loading {
  padding: 2rem;
  text-align: center;
  color: var(--vp-c-text-2);
}
</style>
